### ISSUE TITLE
Snmp alert notification is not working when authentication is enabled

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/notifier#135]
snmp alert notification is not delivered when authentication is enabled, looks like some problem in pycrypto package. 

problem is python2-pyasn1 and python2-crypto is needed as a dependency for pysnmp.

**Comment by GowthamShanmugam** [comment]
@TimothyAsir

**Comment by TimothyAsirJeyasing** [comment]
Earlier Ansible had a dependency to python-crypto package. So we get the package installed automatically during tendrl package installation.
Yesterday (25th Oct 2017) Ansible released a newer version 2.4.1 of ansible package which now uses the cryptography module to implement vault instead of the older pycrypto module.

**Comment by GowthamShanmugam** [comment]
This issue is fixed so i am closing this
